### ISSUE TITLE
Sleeping until next scan loop

### ISSUE THREAD

**Issue by bdog720** [MatterVN/ModbusTCP2MQTT#16]
I've been running into an issue (generally overnight) where the script fails to communicate with the inverter and displays the below message and then never seems to be able to reconnect. The only way I've been able to fix this is to restart the add-on

WARNING:root:Failed to scrape inverter, sleeping until next scan
DEBUG:pymodbus.transaction:Current transaction state - TRANSACTION_COMPLETE
DEBUG:pymodbus.transaction:Running transaction 1291
DEBUG:pymodbus.transaction:SEND: 0x5 0xb 0x0 0x0 0x0 0x6 0x1 0x4 0x13 0x88 0x0 0x64
DEBUG:pymodbus.client.sync:New Transaction state 'SENDING'
DEBUG:pymodbus.transaction:Changing transaction state from 'SENDING' to 'WAITING FOR REPLY'
DEBUG:pymodbus.transaction:Changing transaction state from 'WAITING FOR REPLY' to 'PROCESSING REPLY'
DEBUG:pymodbus.transaction:RECV: 
DEBUG:pymodbus.framer.socket_framer:Processing: 
DEBUG:pymodbus.transaction:Getting transaction 1291
DEBUG:pymodbus.transaction:Changing transaction state from 'PROCESSING REPLY' to 'TRANSACTION_COMPLETE'
WARNING:root:Modbus connection failed
WARNING:root:Failed to scrape inverter, sleeping until next scan

**Comment by mattkerrison** [comment]
I've got this issue too, anyone got a solution?

**Comment by ttvt** [comment]
Try the latest commit version.
