### ISSUE TITLE
Is it possible to connect SG12RT?

### ISSUE THREAD

**Issue by hultis** [MatterVN/ModbusTCP2MQTT#32]
Would me grateful!

**Comment by hultis** [comment]
I've been trying SG10RT but get this in the log:
[22:35:41] INFO: Configured'core-mosquitto' mqtt broker.
INFO:root:Create SungrowModbusTcpClient. Model: sungrow-sg10rt
ERROR:pymodbus.client.sync:Connection to (192.168.3.252, 502) failed: timed out
INFO:root:Modbus connected
INFO:root:Configured MQTT Client
INFO:root:Publish Home Assistant Discovery message

**Comment by ttvt** [comment]
Try the 0.3 and let me know if it's work.
