### ISSUE TITLE
Integration effecting isolarcloud app data

### ISSUE THREAD

**Issue by sEdsKi** [MatterVN/ModbusTCP2MQTT#44]
Since updating, the app I use to view solar inverter data directly is behaving strangely.

It's either disconnected from the internet and not uploading the data. Constant grid draw is incorrect and incorrect PV and lpad.

![Screenshot_20220802-191335~2](https://user-images.githubusercontent.com/98076159/182343744-2e76fb44-dc07-4216-a926-01b62ecd7d36.png)

![Screenshot_20220802-191340~2](https://user-images.githubusercontent.com/98076159/182343779-2deab800-a19c-4553-b086-8953268c3a66.png)

**Comment by highground88** [comment]
![Screenshot_20220802-205130](https://user-images.githubusercontent.com/5027269/182357867-7d902d15-dd5b-4aa4-a5eb-ab7a1085ea59.png)

Mine is running on the latest version with no apparent reading issues. But a week or two ago, I noticed that my inverter was showing as offline on iSolarCloud for a few days. Unsure if it was coincidental, but this was similar timings to the update. I removed the add-on and reinstalled (removed any remnants) and everything appears working again.

**Comment by sEdsKi** [comment]
What equipment do you have?

I have the sg8k-d with wifi dongle

**Comment by highground88** [comment]
Exactly the same mate.

**Comment by sEdsKi** [comment]
> highground88

Could you share your config settings?
I have just removed the addon and will now reinstall it.

**Comment by sEdsKi** [comment]
I've reset the inverter hardware and reinstalled the add-on which seems to have reset everything to normal. Data looks normal for yesterday. Today I see the isolarcloud app stopped receiving data at 12.20pm

![Screenshot_20220805-165648](https://user-images.githubusercontent.com/98076159/183020236-80ac1bd3-cb8f-4a43-91ac-cb767a8392ec.png)

![Screenshot_20220805-165635~2](https://user-images.githubusercontent.com/98076159/183020255-24f6959d-7742-4e36-8c0c-09c4f0672b4b.png)
 
The net light on the wifi dongle is off.

Data is still being received by Home Assistant

![Screenshot_20220805-170137](https://user-images.githubusercontent.com/98076159/183020724-807adf97-aa45-4cdb-bcfa-e231224461b5.png)

Can't say it's this add-on causing that problem... But I would guess it is.

**Comment by sEdsKi** [comment]
Have pulled out the Wifi dongle and replaced it. Data now flowing into iSolarCloud App and HA.
I will update if anything changes.

**Comment by helikopter1909** [comment]
I have same problem after update 2022.9.6 and to new config for mtqq source. data in ha available and not in isolarcloud App. Has anybody a solution? How do config your mtqq sensor in configuration.yaml?

**Comment by helikopter1909** [comment]
The described problem is a bug in the isolarcloud app and not a problem with the mod.

**Comment by michael-letcher** [comment]
Having the same issue with my inverter. After a period of time, the app stops getting data and only after stopping the HA Add-on does it start again.

**Comment by jsword** [comment]
I've seen the same think after power/network outages. iSolar cloud stops but HA still receives data. Pulling the dongle fixes it.
