### ISSUE TITLE
Variable IP address in configuration?

### ISSUE THREAD

**Issue by simongoudie** [MatterVN/ModbusTCP2MQTT#46]
My inverter regularly changes IP address (and MAC address, meaning I can't assign a static IP), so I have to manually update 'Inverter_host' in the config frequently so that the addon can find it again.

I can find the correct IP by pinging and can record this as an entity in HASS, but not sure if I can use this value in the addon configuration?

In short, is there a way that 'Inverter_host' in the config/yaml can point to a HASS entity with the current IP, rather than using just a manually-entered IP address?

**Comment by ttvt** [comment]
Config your router to assign inverter fix IP. You can also try to use inverter's name instead of inverter's IP.
