### ISSUE TITLE
Mosquitto refusing connections

### ISSUE THREAD

**Issue by bleughb** [MatterVN/ModbusTCP2MQTT#61]
Hi,

Fairly new to home assistant and everything - 
BUT - I can't get my head around this one
have configured a few other MQTT devices ok, but this Modbus addon seems to not want to play nicely...
and i'm not having much success 'googling' answers

it's publishing everything OK - but, the mosquitto broker is refusing to receive the data......

New connection from 127.0.0.1:55070 on port 1883.  
2023-05-22 07:29:11: Client <unknown> closed its connection.

any advice? - 
In Mosquitto
I have 'require certificate' unticked
nothing in 'logins' 
1883 is my Normal MQTT port

I've noted that Sungather has some options for MQQT user / passwords etc but there seems to be nothing for this

**Comment by ttvt** [comment]
The MQTT connection will broken if you reinstall MQTT. If this happen, please uninstall this addon and reinstall it.
